import { buildDatabase } from './src/data/mockData.js';
import { hydrate } from './src/core/store.js';
const db = buildDatabase();
hydrate(db);
const one = (arr) => arr[0];
console.log('workflows:', JSON.stringify(one(db.workflows), null, 1).slice(0, 700));
console.log('runs:', JSON.stringify(one(db.runs), null, 1).slice(0, 900));
console.log('jobs:', JSON.stringify(one(db.jobs), null, 1).slice(0, 900));
console.log('artifacts:', JSON.stringify(one(db.artifacts), null, 1).slice(0, 400));
console.log('caches:', JSON.stringify(one(db.caches), null, 1).slice(0, 400));
console.log('secrets:', JSON.stringify(one(db.secrets), null, 1).slice(0, 400));
console.log('variables:', JSON.stringify(one(db.variables), null, 1).slice(0, 400));
console.log('runners:', JSON.stringify(one(db.runners), null, 1).slice(0, 500));
console.log('environments:', JSON.stringify(one(db.environments), null, 1).slice(0, 600));
console.log('deployments:', JSON.stringify(one(db.deployments), null, 1).slice(0, 500));
import { STEP_LOGS } from './src/data/mockData.js';
const keys=[...STEP_LOGS.keys()].slice(0,2);
console.log('STEP_LOGS keys:', STEP_LOGS.size, keys);
console.log('step log sample:', JSON.stringify(STEP_LOGS.get(keys[0]), null, 1).slice(0, 800));
