/**
 * RedGet — notifications.
 *
 * Notifications are generated by real actions in this browser: a follow, a
 * star, a fork, a comment on your issue, a review on your pull request, a
 * mention. They are stored per recipient so the bell badge in the header is an
 * honest unread count instead of a hard-coded number.
 *
 *   { id, to, from, kind, text, href, at, read }
 *
 * `kind` drives the icon: follow | star | fork | issue | pull | comment |
 * review | mention | release | discussion | system
 */

import { DB, ME, saveDB } from '../state.js';
import { uid, timeAgo } from './util.js';

var MAX_NOTIFICATIONS = 200;

export var NOTIFICATION_ICONS = {
  follow: 'person',
  star: 'star',
  fork: 'fork',
  issue: 'issue',
  pull: 'redPR',
  comment: 'comment',
  review: 'redPR',
  mention: 'megaphone',
  release: 'tag',
  discussion: 'commentDiscussion',
  system: 'shield',
};

/** Append a notification for `to`. Never notifies the actor about themselves. */
export function notify(entry) {
  if (!entry || !entry.to) return null;
  if (ME && entry.to === ME.username) return null;
  if (!DB.notifications) DB.notifications = [];
  var record = {
    id: uid('notif'),
    to: entry.to,
    from: entry.from || (ME ? ME.username : ''),
    kind: entry.kind || 'system',
    text: entry.text || '',
    href: entry.href || '/',
    at: entry.at || Date.now(),
    read: false,
  };
  DB.notifications.unshift(record);
  if (DB.notifications.length > MAX_NOTIFICATIONS) DB.notifications.length = MAX_NOTIFICATIONS;
  saveDB();
  return record;
}

export function notificationsFor(username) {
  var name = username || (ME && ME.username);
  if (!name) return [];
  return (DB.notifications || [])
    .filter(function (n) { return n.to === name; })
    .sort(function (a, b) { return b.at - a.at; });
}

export function unreadCount(username) {
  return notificationsFor(username).filter(function (n) { return !n.read; }).length;
}

export function markRead(id) {
  var found = (DB.notifications || []).filter(function (n) { return n.id === id; })[0];
  if (found) { found.read = true; saveDB(); }
  return found;
}

export function markAllRead(username) {
  var name = username || (ME && ME.username);
  var changed = false;
  (DB.notifications || []).forEach(function (n) {
    if (n.to === name && !n.read) { n.read = true; changed = true; }
  });
  if (changed) saveDB();
  return changed;
}

export function deleteNotification(id) {
  DB.notifications = (DB.notifications || []).filter(function (n) { return n.id !== id; });
  saveDB();
}

export function clearNotifications(username) {
  var name = username || (ME && ME.username);
  DB.notifications = (DB.notifications || []).filter(function (n) { return n.to !== name; });
  saveDB();
}

/** One notification row, as used by the header dropdown and the inbox. */
export function notificationLabel(n) {
  return (n.from ? n.from + ' ' : '') + n.text;
}

export function notificationIcon(n) {
  return NOTIFICATION_ICONS[n.kind] || 'bell';
}

export function notificationAge(n) {
  return timeAgo(n.at);
}
